const {
  JWT_SECRET_KEY,
  JWT_EXPIRATION_TIME,
  JWT_SALT,
  AUTH_RESET_ORIGINAL_URL,
  ADD_USER_INVITE_URL,
  FILE_UPLOAD_INVITE_URL,
  pc_ADMIN_BASE_URL,
  PUBLIC_FILE_UPLOAD,
  WAITING_USER_EMAIL_EXPIRATION,
  AUTHENTICATION_CODE_EXPIRATION_TIME,
  DATA_ENTRY_USER_SET_PASSWORD_EXPIRATION,
  MAIL,
  RATE_LIMIT_WINDOW,
  SINGLE_USER_LOGIN_RATE_LIMIT,
  MULTIPLE_USER_LOGIN_RATE_LIMIT,
} = process.env;

export const authConfig = {
  salt: parseInt(JWT_SALT) || 10,
  expiration_time: JWT_EXPIRATION_TIME || '7d',
  jwt_key: JWT_SECRET_KEY || '@PEIMR@SO',
  AUTH_RESET_ORIGINAL_URL: AUTH_RESET_ORIGINAL_URL || '/password/reset/',
  ADD_USER_INVITE_URL: ADD_USER_INVITE_URL || '/user/set-password',
  FILE_UPLOAD_INVITE_URL: FILE_UPLOAD_INVITE_URL || '/user/file-upload',
  pc_ADMIN_BASE_URL: pc_ADMIN_BASE_URL || 'http://35.176.74.3',
  PUBLIC_FILE_UPLOAD: PUBLIC_FILE_UPLOAD || '/file-upload',
  WAITING_USER_EMAIL_EXPIRATION: WAITING_USER_EMAIL_EXPIRATION || '1', //in days
  DATA_ENTRY_USER_SET_PASSWORD_EXPIRATION: DATA_ENTRY_USER_SET_PASSWORD_EXPIRATION || '1', //in days
  AUTHENTICATION_CODE_EXPIRATION_TIME: AUTHENTICATION_CODE_EXPIRATION_TIME || 5, // in minutes
  MAIL: MAIL || 'info@pc.com',
  rateLimitWindow: parseInt(RATE_LIMIT_WINDOW) || 1, // in minutes
  singleUserLoginRateLimit: parseInt(SINGLE_USER_LOGIN_RATE_LIMIT) || 5,
  multipleUserLoginRateLimit: parseInt(MULTIPLE_USER_LOGIN_RATE_LIMIT) || 3,
};
